"""The synthetic test clip from decision 12.1, and the rule set it is judged by.

6 s, 1080x1920, 30 fps: a slowly moving colour gradient with a skin-toned face
ellipse (eyes and mouth drawn) in the top third, and a mono audio track with six
0.3 s tone bursts at known times. Generated by ffmpeg on demand; never committed.
`tests/conftest.py` and `shortsmith.smoke` both call `make_fixture`.

`smoke_specs` is the fixture-shaped grammar (ticket 009): the fake planner's plan
names every tier-1 kind in six seconds, which no real style's beat numbers allow
(explainer's 0.7 s minimum and 2.0-3.2 s mean cannot hold eleven beats in 6 s), so
the smoke and the tests that run the fake plan through the pipeline validate it
against a copy of `explainer` whose beat, asset-count and ramp numbers are scaled
to the clip. Nothing else changes: typography, PIP, palette, finale and every other
number stay the shipped spec's, the validator and the pipeline never know a fixture
exists, and the T3 finale check stays unscaled.
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from shortsmith import styles
from shortsmith.ffmpeg import FFMPEG, run
from shortsmith.styles import StyleSpec

DURATION_S = 6.0
WIDTH, HEIGHT, FPS = 1080, 1920, 30

BURST_TIMES: tuple[float, ...] = (0.2, 1.2, 2.2, 3.2, 4.2, 5.2)
BURST_LEN_S = 0.3
BURST_HZ = 880

# Face ellipse: centre (540, 380), semi-axes 220 x 230 -> spans y 150..610 (top third).
FACE_CENTER = (540, 380)
FACE_HALF = (220, 230)
FACE_COLOR = (232, 184, 150)  # 0xE8B896
EYE_CENTERS = ((480, 355), (600, 355))
EYE_SIZE = (40, 30)
MOUTH_BOX = (490, 470, 100, 22)  # x, y, w, h

# The numbers a six-second, eleven-beat plan cannot meet, and what they become.
SMOKE_BEATS: dict[str, float] = {
    "min_s": 0.4,  # ten 0.5 s beats
    "target_mean_s": 0.55,
    "mean_min_s": 0.5,  # 6 s / 11 beats = 0.545 s
    "mean_max_s": 0.7,
    "cold_open_min_s": 0.4,
    "cold_open_max_s": 0.6,
    "hook_cards_min_s": 0.4,
    "hook_cards_max_s": 0.6,
}
SMOKE_BROLL: dict[str, int] = {
    "unique_assets_min_per_60s": 10,  # -> 1 in 6 s
    "unique_assets_max_per_60s": 100,  # -> 10 in 6 s; the fake names 8
}
SMOKE_SOUND: dict[str, float] = {
    "ramp_min_s": 0.4,  # the fake's curve rises over 0.5 s
    "cues_max_per_60s": 60,  # -> 6 in 6 s; the fake places 5
}


def smoke_specs(specs: Mapping[str, StyleSpec]) -> dict[str, StyleSpec]:
    """`specs` with the default style replaced by its fixture-shaped copy."""
    base = specs[styles.DEFAULT]
    scaled = base.model_copy(deep=True)
    for name, value in SMOKE_BEATS.items():
        setattr(scaled.beats, name, value)
    for name, count in SMOKE_BROLL.items():
        setattr(scaled.broll, name, count)
    for name, value in SMOKE_SOUND.items():
        setattr(scaled.sound, name, value)
    return {**specs, styles.DEFAULT: scaled}


def make_fixture(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fx, fy = FACE_HALF
    face_w, face_h = 2 * fx, 2 * fy
    face_x, face_y = FACE_CENTER[0] - fx, FACE_CENTER[1] - fy
    face_hex = "0x{:02X}{:02X}{:02X}".format(*FACE_COLOR)
    eye_w, eye_h = EYE_SIZE
    eyes = ",".join(
        f"drawbox=x={ex - eye_w // 2}:y={ey - eye_h // 2}:w={eye_w}:h={eye_h}"
        ":color=0x2B1B12:t=fill"
        for ex, ey in EYE_CENTERS
    )
    mx, my, mw, mh = MOUTH_BOX
    mouth = f"drawbox=x={mx}:y={my}:w={mw}:h={mh}:color=0x8B3A3A:t=fill"
    ellipse_alpha = f"255*lt(pow((X-{fx})/{fx}\\,2)+pow((Y-{fy})/{fy}\\,2)\\,1)"
    graph = ";".join(
        [
            "[0:v]format=yuv420p[bg]",
            f"[1:v]format=rgba,geq=r='r(X\\,Y)':g='g(X\\,Y)':b='b(X\\,Y)':a='{ellipse_alpha}'[face]",
            f"[bg][face]overlay={face_x}:{face_y},{eyes},{mouth},format=yuv420p[v]",
        ]
    )
    burst_end = 0.2 + BURST_LEN_S
    audio = (
        f"aevalsrc=exprs='0.5*sin(2*PI*{BURST_HZ}*t)*between(mod(t\\,1)\\,0.2\\,{burst_end})'"
        f":s=48000:c=mono:d={DURATION_S}"
    )
    run(
        [
            FFMPEG,
            "-v",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"gradients=s={WIDTH}x{HEIGHT}:r={FPS}:d={DURATION_S}:speed=0.03:seed=7",
            "-f",
            "lavfi",
            "-i",
            f"color=c={face_hex}:s={face_w}x{face_h}:r={FPS}:d={DURATION_S}",
            "-f",
            "lavfi",
            "-i",
            audio,
            "-filter_complex",
            graph,
            "-map",
            "[v]",
            "-map",
            "2:a",
            "-t",
            f"{DURATION_S}",
            "-r",
            str(FPS),
            "-fps_mode",
            "cfr",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "30",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-b:a",
            "64k",
            "-movflags",
            "+faststart",
            str(path),
        ]
    )
    return path


def make_clip(
    path: Path,
    *,
    duration_s: float,
    width: int = 1080,
    height: int = 1920,
    amplitude: float = 0.3,
    audio: bool = True,
    fps: int = 30,
) -> Path:
    """A cheap synthetic clip for boundary tests: flat colour, one sine tone (or none).

    `.mov` outputs carry PCM audio so a tiny `amplitude` survives encoding exactly;
    `.mp4` outputs use AAC. `audio=False` writes a clip with no audio stream at all.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    argv = [
        FFMPEG,
        "-v",
        "error",
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c=0x3355AA:s={width}x{height}:r={fps}:d={duration_s}",
    ]
    if audio:
        argv += [
            "-f",
            "lavfi",
            "-i",
            f"aevalsrc=exprs='{amplitude}*sin(2*PI*440*t)':s=48000:c=mono:d={duration_s}",
            "-map",
            "0:v",
            "-map",
            "1:a",
        ]
    argv += ["-t", f"{duration_s}", "-c:v", "libx264", "-preset", "ultrafast", "-crf", "35"]
    argv += ["-pix_fmt", "yuv420p"]
    if audio:
        argv += ["-c:a", "pcm_s16le"] if path.suffix.lower() == ".mov" else ["-c:a", "aac"]
    argv.append(str(path))
    run(argv)
    return path


def make_image(path: Path, *, width: int, height: int) -> Path:
    """A flat-colour still in the format named by `path`'s suffix (png, jpg, webp)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            FFMPEG,
            "-v",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"color=c=0xAA5533:s={width}x{height}",
            "-frames:v",
            "1",
            str(path),
        ]
    )
    return path
