"""The synthetic test clip from decision 12.1, and the rule set it is judged by.

6 s, 1080x1920, 30 fps: a slowly moving colour gradient with a skin-toned face
ellipse in the top third, and a mono audio track with six 0.3 s tone bursts at known
times. Generated by ffmpeg on demand; never committed. `tests/conftest.py` and
`shortsmith.smoke` both call `make_fixture`.

Fixture v2, 25 Sep 2026 (ticket 013), elaborating 12.1's "moving colour gradient with
a drawn 'face' ellipse in the top third (so the face detector finds it)": the face
ellipse now wears a dark hair cap, brows, larger eyes, a nose shadow and a dark
collar under the chin, because OpenCV's frontal-face cascade at its documented
defaults missed the flat ellipse on a quarter of the strip stills whenever the
gradient behind it was bright; and the gradient's three colours are written out,
because this ffmpeg build's `gradients` source ignores `seed`, so a seeded clip was a
new clip every session. With both, the decoded frames are identical across
generations and the cascade found the face on 80 of 80 stills over ten of them. The
detector was not loosened; the drawing met it.

`smoke_specs` is the fixture-shaped grammar (ticket 009): the fake planner's plan
names every tier-1 kind in six seconds, which no real style's beat numbers allow
(explainer's 0.7 s minimum and 2.0-3.2 s mean cannot hold eleven beats in 6 s), so
the smoke and the tests that run the fake plan through the pipeline validate it
against a copy of `explainer` whose beat, asset-count and ramp numbers are scaled
to the clip. Nothing else changes: typography, PIP, palette, finale and every other
number stay the shipped spec's, the validator and the pipeline never know a fixture
exists, and the T3 finale check stays unscaled.
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from shortsmith import styles
from shortsmith.ffmpeg import FFMPEG, run
from shortsmith.styles import StyleSpec

DURATION_S = 6.0
WIDTH, HEIGHT, FPS = 1080, 1920, 30

BURST_TIMES: tuple[float, ...] = (0.2, 1.2, 2.2, 3.2, 4.2, 5.2)
BURST_LEN_S = 0.3
BURST_HZ = 880

# The gradient's colours, written out: `seed` alone does not pin them (fixture v2).
GRADIENT_COLORS = ("0x6A3FD8", "0xE86A9A", "0x2E8B6E")
# Face ellipse: centre (540, 380), semi-axes 220 x 230 -> spans y 150..610 (top third).
FACE_CENTER = (540, 380)
FACE_HALF = (220, 230)
FACE_COLOR = (232, 184, 150)  # 0xE8B896
# Fixture v2: the hair cap is the same ellipse in the hair colour, drawn first, this
# far above the face; brows sit above the eyes; the nose shadow and collar are boxes.
HAIR_COLOR = (43, 27, 18)  # 0x2B1B12, the eye and brow colour too
HAIR_LIFT = 70
EYE_CENTERS = ((480, 355), (600, 355))
EYE_SIZE = (60, 34)
BROW_SIZE, BROW_LIFT = (110, 16), 42
NOSE_BOX = (532, 395, 16, 70)  # x, y, w, h; below the ellipse centre, above the mouth
NOSE_COLOR = "0xC9977A"
MOUTH_BOX = (490, 470, 100, 22)  # x, y, w, h
COLLAR_BOX = (400, 600, 280, 170)  # the dark shirt under the chin
COLLAR_COLOR = "0x1E2A44"

# The numbers a six-second, eleven-beat plan cannot meet, and what they become.
SMOKE_BEATS: dict[str, float] = {
    "min_s": 0.4,  # ten 0.5 s beats
    "target_mean_s": 0.55,
    "mean_min_s": 0.5,  # 6 s / 11 beats = 0.545 s
    "mean_max_s": 0.7,
    "cold_open_min_s": 0.4,
    "cold_open_max_s": 0.6,
    "hook_cards_min_s": 0.4,
    "hook_cards_max_s": 0.6,
}
SMOKE_BROLL: dict[str, int] = {
    "unique_assets_min_per_60s": 10,  # -> 1 in 6 s
    "unique_assets_max_per_60s": 100,  # -> 10 in 6 s; the fake names 7 (020: no map asset)
}
SMOKE_SOUND: dict[str, float] = {
    "ramp_min_s": 0.4,  # the fake's curve rises over 0.5 s
    "cues_max_per_60s": 60,  # -> 6 in 6 s; the fake places 5
}


def smoke_specs(specs: Mapping[str, StyleSpec], name: str = styles.DEFAULT) -> dict[str, StyleSpec]:
    """`specs` with the style `name` (the default unless told otherwise) replaced by its
    fixture-shaped copy. Ticket 048 renders the fixture under the `hitech` draft, so
    the draft is judged by its own numbers scaled the same way; every other spec is
    handed back untouched."""
    base = specs[name]
    scaled = base.model_copy(deep=True)
    for field, value in SMOKE_BEATS.items():
        setattr(scaled.beats, field, value)
    for field, count in SMOKE_BROLL.items():
        setattr(scaled.broll, field, count)
    for field, value in SMOKE_SOUND.items():
        setattr(scaled.sound, field, value)
    return {**specs, name: scaled}


# --- the synthesised audio catalogue (ticket 022; decisions 7.2, 12.1) ------------------
#
# The real seed library is hand-sourced and hand-listened by the operator (ticket 025);
# tests and the smoke need a catalogue that exists on any machine and is never committed,
# so `make_catalogue` synthesises one with ffmpeg exactly as `make_fixture` synthesises
# the clip: tone beds and click SFX, tagged so the fake plan's bed query and every cue
# intent it names resolve. The sound director never knows a fixture exists.

# id, theme tags, mood tags, energy, drop points, fundamental Hz. The fundamentals sit
# under the 250 Hz-4 kHz speech band, as a real bed's energy does: a bed that crowded the
# band would fail the 7.3 speech-band margin, which is the point of that check.
BedRow = tuple[str, tuple[str, ...], tuple[str, ...], int, tuple[float, ...], int]
CATALOGUE_BEDS: tuple[BedRow, ...] = (
    ("bed_tech_curious", ("tech", "science"), ("curious", "bright"), 3, (1.0, 3.5), 110),
    ("bed_tech_tense", ("tech",), ("tense", "dark"), 4, (2.0,), 82),
    ("bed_history_calm", ("history",), ("calm",), 1, (), 65),
)  # fmt: skip
# id, intent tags, click Hz. The first three carry the 7.1 floor-hit classes.
CATALOGUE_SFX: tuple[tuple[str, tuple[str, ...], int], ...] = (
    ("sfx_bass_hit", ("bass", "cold_open_hit", "reveal"), 70),
    ("sfx_drum_hit", ("drum", "money", "finale_hit"), 95),
    ("sfx_thump", ("thump", "card_fly_in"), 130),
    ("sfx_tick", ("popup_tick", "tick"), 1400),
    ("sfx_changeover", ("changeover",), 620),
)
CATALOGUE_BED_S = 8.0
CATALOGUE_SFX_S = 0.4
CATALOGUE_NAME = "catalog.yaml"
CATALOGUE_LICENCE = "CC0-1.0"
CATALOGUE_SOURCE = "synthetic"


def make_wav(path: Path, *, expr: str, duration_s: float) -> Path:
    """A 48 kHz mono 16-bit WAV of the `aevalsrc` expression `expr` in `t`: the
    catalogue's beds and clicks, and the 023 sweep offenders `tests/conftest.py` builds."""
    run(
        [
            FFMPEG, "-v", "error", "-y", "-f", "lavfi",
            "-i", f"aevalsrc=exprs='{expr}':s=48000:c=mono:d={duration_s:g}",
            "-c:a", "pcm_s16le", str(path),
        ],  # fmt: skip
    )
    return path


def make_catalogue(root: Path) -> Path:
    """Write `<root>/catalog.yaml` and `<root>/files/*.wav`; return the catalogue path.

    Beds are a steady tone under a slow amplitude wobble, so a bed has a measurable RMS
    and loops without a seam; SFX are short decaying clicks, so a cue has a peak the
    level match can aim at. Neither is music: the catalogue is measured, not listened to.
    """
    files = root / "files"
    files.mkdir(parents=True, exist_ok=True)
    entries: list[str] = []
    for name, theme, mood, energy, drops, hz in CATALOGUE_BEDS:
        make_wav(
            files / f"{name}.wav",
            expr=(
                f"(0.25*sin(2*PI*{hz}*t)+0.05*sin(2*PI*{3 * hz}*t))"
                "*(0.7+0.3*sin(2*PI*0.5*t))"
            ),
            duration_s=CATALOGUE_BED_S,
        )
        entries.append(
            _entry_yaml(
                name, kind="bed", duration_s=CATALOGUE_BED_S, energy=energy,
                theme=theme, mood=mood, intent=(), drops=drops, loop_ok=True,
            )  # fmt: skip
        )
    for name, intent, hz in CATALOGUE_SFX:
        make_wav(
            files / f"{name}.wav",
            expr=f"0.8*sin(2*PI*{hz}*t)*exp(-14*t)",
            duration_s=CATALOGUE_SFX_S,
        )
        entries.append(
            _entry_yaml(
                name, kind="sfx", duration_s=CATALOGUE_SFX_S, energy=3,
                theme=(), mood=(), intent=intent, drops=(), loop_ok=False,
            )  # fmt: skip
        )
    path = root / CATALOGUE_NAME
    path.write_text("entries:\n" + "".join(entries), encoding="utf-8")
    return path


def _entry_yaml(
    name: str, *, kind: str, duration_s: float, energy: int, theme: tuple[str, ...],
    mood: tuple[str, ...], intent: tuple[str, ...], drops: tuple[float, ...], loop_ok: bool,
) -> str:  # fmt: skip
    def listed(values: tuple[str, ...] | tuple[float, ...]) -> str:
        return "[" + ", ".join(f"{v}" for v in values) + "]"

    return (
        f"  - id: {name}\n"
        f"    kind: {kind}\n"
        f"    file: files/{name}.wav\n"
        f"    source: {CATALOGUE_SOURCE}\n"
        f"    source_url: https://example.invalid/fixture/{name}\n"
        f"    licence: {CATALOGUE_LICENCE}\n"
        f"    author: shortsmith fixture\n"
        f"    duration_s: {duration_s:g}\n"
        f"    tags:\n"
        f"      theme: {listed(theme)}\n"
        f"      mood: {listed(mood)}\n"
        f"      intent: {listed(intent)}\n"
        f"    drop_points_s: {listed(drops)}\n"
        f"    loop_ok: {str(loop_ok).lower()}\n"
        f"    energy: {energy}\n"
    )


def make_fixture(path: Path, *, face: bool = True) -> Path:
    """The 12.1 clip. `face=False` leaves the ellipse out (013): the same gradient and
    bursts with nothing for the detector to find, so the early failure is testable."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fx, fy = FACE_HALF
    face_w, face_h = 2 * fx, 2 * fy
    face_x, face_y = FACE_CENTER[0] - fx, FACE_CENTER[1] - fy
    face_hex = "0x{:02X}{:02X}{:02X}".format(*FACE_COLOR)
    hair_hex = "0x{:02X}{:02X}{:02X}".format(*HAIR_COLOR)

    def box(x: int, y: int, w: int, h: int, color: str) -> str:
        return f"drawbox=x={x}:y={y}:w={w}:h={h}:color={color}:t=fill"

    eye_w, eye_h = EYE_SIZE
    brow_w, brow_h = BROW_SIZE
    eyes = ",".join(box(ex - eye_w // 2, ey - eye_h // 2, eye_w, eye_h, hair_hex)
                    for ex, ey in EYE_CENTERS)  # fmt: skip
    brows = ",".join(box(ex - brow_w // 2, ey - BROW_LIFT - brow_h // 2, brow_w, brow_h, hair_hex)
                     for ex, ey in EYE_CENTERS)  # fmt: skip
    nose = box(*NOSE_BOX, NOSE_COLOR)
    mouth = box(*MOUTH_BOX, "0x8B3A3A")
    collar = box(*COLLAR_BOX, COLLAR_COLOR)
    ellipse_alpha = f"255*lt(pow((X-{fx})/{fx}\\,2)+pow((Y-{fy})/{fy}\\,2)\\,1)"
    ellipse = f"format=rgba,geq=r='r(X\\,Y)':g='g(X\\,Y)':b='b(X\\,Y)':a='{ellipse_alpha}'"
    if face:
        graph = ";".join(
            [
                f"[0:v]format=yuv420p,{collar}[bg]",
                f"[1:v]{ellipse}[face]",
                f"[2:v]{ellipse}[hair]",
                f"[bg][hair]overlay={face_x}:{face_y - HAIR_LIFT}[bg1]",
                f"[bg1][face]overlay={face_x}:{face_y},{brows},{eyes},{nose},{mouth},"
                "format=yuv420p[v]",
            ]
        )
        size = f"s={face_w}x{face_h}:r={FPS}:d={DURATION_S}"
        face_input = ["-f", "lavfi", "-i", f"color=c={face_hex}:{size}",
                      "-f", "lavfi", "-i", f"color=c={hair_hex}:{size}"]  # fmt: skip
        audio_map = "3:a"
    else:
        graph = "[0:v]format=yuv420p[v]"
        face_input = []
        audio_map = "1:a"
    colours = ":".join(f"c{i}={c}" for i, c in enumerate(GRADIENT_COLORS))
    gradient = (
        f"gradients=s={WIDTH}x{HEIGHT}:r={FPS}:d={DURATION_S}:speed=0.03:seed=7"
        f":nb_colors={len(GRADIENT_COLORS)}:{colours}"
    )
    burst_end = 0.2 + BURST_LEN_S
    audio = (
        f"aevalsrc=exprs='0.5*sin(2*PI*{BURST_HZ}*t)*between(mod(t\\,1)\\,0.2\\,{burst_end})'"
        f":s=48000:c=mono:d={DURATION_S}"
    )
    run(
        [
            FFMPEG,
            "-v",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            gradient,
            *face_input,
            "-f",
            "lavfi",
            "-i",
            audio,
            "-filter_complex",
            graph,
            "-map",
            "[v]",
            "-map",
            audio_map,
            "-t",
            f"{DURATION_S}",
            "-r",
            str(FPS),
            "-fps_mode",
            "cfr",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "30",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-b:a",
            "64k",
            "-movflags",
            "+faststart",
            str(path),
        ]
    )
    return path


def make_clip(
    path: Path,
    *,
    duration_s: float,
    width: int = 1080,
    height: int = 1920,
    amplitude: float = 0.3,
    audio: bool = True,
    fps: int = 30,
) -> Path:
    """A cheap synthetic clip for boundary tests: flat colour, one sine tone (or none).

    `.mov` outputs carry PCM audio so a tiny `amplitude` survives encoding exactly;
    `.mp4` outputs use AAC. `audio=False` writes a clip with no audio stream at all.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    argv = [
        FFMPEG,
        "-v",
        "error",
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c=0x3355AA:s={width}x{height}:r={fps}:d={duration_s}",
    ]
    if audio:
        argv += [
            "-f",
            "lavfi",
            "-i",
            f"aevalsrc=exprs='{amplitude}*sin(2*PI*440*t)':s=48000:c=mono:d={duration_s}",
            "-map",
            "0:v",
            "-map",
            "1:a",
        ]
    argv += ["-t", f"{duration_s}", "-c:v", "libx264", "-preset", "ultrafast", "-crf", "35"]
    argv += ["-pix_fmt", "yuv420p"]
    if audio:
        argv += ["-c:a", "pcm_s16le"] if path.suffix.lower() == ".mov" else ["-c:a", "aac"]
    argv.append(str(path))
    run(argv)
    return path


def make_image(path: Path, *, width: int, height: int) -> Path:
    """A flat-colour still in the format named by `path`'s suffix (png, jpg, webp)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            FFMPEG,
            "-v",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"color=c=0xAA5533:s={width}x{height}",
            "-frames:v",
            "1",
            str(path),
        ]
    )
    return path
