"""The synthetic test clip from decision 12.1.

6 s, 1080x1920, 30 fps: a slowly moving colour gradient with a skin-toned face
ellipse (eyes and mouth drawn) in the top third, and a mono audio track with six
0.3 s tone bursts at known times. Generated by ffmpeg on demand; never committed.
`tests/conftest.py` and `shortsmith.smoke` both call `make_fixture`.
"""

from __future__ import annotations

from pathlib import Path

from shortsmith.ffmpeg import FFMPEG, run

DURATION_S = 6.0
WIDTH, HEIGHT, FPS = 1080, 1920, 30

BURST_TIMES: tuple[float, ...] = (0.2, 1.2, 2.2, 3.2, 4.2, 5.2)
BURST_LEN_S = 0.3
BURST_HZ = 880

# Face ellipse: centre (540, 380), semi-axes 220 x 230 -> spans y 150..610 (top third).
FACE_CENTER = (540, 380)
FACE_HALF = (220, 230)
FACE_COLOR = (232, 184, 150)  # 0xE8B896
EYE_CENTERS = ((480, 355), (600, 355))
EYE_SIZE = (40, 30)
MOUTH_BOX = (490, 470, 100, 22)  # x, y, w, h


def make_fixture(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fx, fy = FACE_HALF
    face_w, face_h = 2 * fx, 2 * fy
    face_x, face_y = FACE_CENTER[0] - fx, FACE_CENTER[1] - fy
    face_hex = "0x{:02X}{:02X}{:02X}".format(*FACE_COLOR)
    eye_w, eye_h = EYE_SIZE
    eyes = ",".join(
        f"drawbox=x={ex - eye_w // 2}:y={ey - eye_h // 2}:w={eye_w}:h={eye_h}"
        ":color=0x2B1B12:t=fill"
        for ex, ey in EYE_CENTERS
    )
    mx, my, mw, mh = MOUTH_BOX
    mouth = f"drawbox=x={mx}:y={my}:w={mw}:h={mh}:color=0x8B3A3A:t=fill"
    ellipse_alpha = f"255*lt(pow((X-{fx})/{fx}\\,2)+pow((Y-{fy})/{fy}\\,2)\\,1)"
    graph = ";".join(
        [
            "[0:v]format=yuv420p[bg]",
            f"[1:v]format=rgba,geq=r='r(X\\,Y)':g='g(X\\,Y)':b='b(X\\,Y)':a='{ellipse_alpha}'[face]",
            f"[bg][face]overlay={face_x}:{face_y},{eyes},{mouth},format=yuv420p[v]",
        ]
    )
    burst_end = 0.2 + BURST_LEN_S
    audio = (
        f"aevalsrc=exprs='0.5*sin(2*PI*{BURST_HZ}*t)*between(mod(t\\,1)\\,0.2\\,{burst_end})'"
        f":s=48000:c=mono:d={DURATION_S}"
    )
    run(
        [
            FFMPEG,
            "-v",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"gradients=s={WIDTH}x{HEIGHT}:r={FPS}:d={DURATION_S}:speed=0.03:seed=7",
            "-f",
            "lavfi",
            "-i",
            f"color=c={face_hex}:s={face_w}x{face_h}:r={FPS}:d={DURATION_S}",
            "-f",
            "lavfi",
            "-i",
            audio,
            "-filter_complex",
            graph,
            "-map",
            "[v]",
            "-map",
            "2:a",
            "-t",
            f"{DURATION_S}",
            "-r",
            str(FPS),
            "-fps_mode",
            "cfr",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "30",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-b:a",
            "64k",
            "-movflags",
            "+faststart",
            str(path),
        ]
    )
    return path
